[package]
name = "myhasher"
version = "0.1.0"
edition = "2021"


[lib]
name = "mylib"
path = "src/myhasher.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"

[dependencies]
hex = "0.4.3"
sha2 = "0.10.2"
clap = { version = "3.2.22", features = ["derive"] }
